@DanielBlog.API_HostAddress = http://localhost:44351

POST https://localhost:44351/api/blogs
Accept: application/json

{
  "title": "My New Blog",
  "content": "This is the content of my new blog.",
  "author": "Daniel"
}
